//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDELINK_WeChatNews
    {
        public System.Guid ID { get; set; }
        public string sTitle { get; set; }
        public string sPictureUrl { get; set; }
        public string sDataUrl { get; set; }
        public string sContent { get; set; }
        public string sDescribe { get; set; }
    }
}
