//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// CDELINK_Client
    /// </summary>
    public partial class CDELINK_Client
    {
    	/// <summary>
        /// 
        /// </summary>
        public System.Guid ID { get; set; }
    	/// <summary>
        /// 手机号码
        /// </summary>
        public string sPhone { get; set; }
    	/// <summary>
        /// 前端会员登录密码
        /// </summary>
        public string sPassWord { get; set; }
    	/// <summary>
        /// 会员绑定的法院的主键ID
        /// </summary>
        public string sCourtId { get; set; }
    	/// <summary>
        /// 状态 0-冻结 1-正常
        /// </summary>
        public int iState { get; set; }
    	/// <summary>
        /// 会员的账户余额
        /// </summary>
        public decimal dPrices { get; set; }
    	/// <summary>
        /// 注册时间
        /// </summary>
        public System.DateTime dRegisterTime { get; set; }
    	/// <summary>
        /// 会员昵称
        /// </summary>
        public string sNickName { get; set; }
    }
}
