//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDELINK_WeChatMenu
    {
        public System.Guid ID { get; set; }
        public string sMenuName { get; set; }
        public string sUrl { get; set; }
        public string sParentMenuId { get; set; }
        public bool bIsDeleted { get; set; }
        public int iType { get; set; }
        public int iOrder { get; set; }
        public string sKey { get; set; }
    }
}
