//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// CDELINK_AdminRole
    /// </summary>
    public partial class CDELINK_AdminRole
    {
    	/// <summary>
        /// ID
        /// </summary>
        public System.Guid ID { get; set; }
    	/// <summary>
        /// 角色名称
        /// </summary>
        public string sRoleName { get; set; }
    	/// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime dInsertTime { get; set; }
    	/// <summary>
        /// 逻辑删除标识
        /// </summary>
        public bool bIsDeleted { get; set; }
    	/// <summary>
        /// 菜单主键ID集合(以逗号隔开)
        /// </summary>
        public string sPowerIds { get; set; }
    }
}
