//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// CDELINK_AdminUser
    /// </summary>
    public partial class CDELINK_AdminUser
    {
    	/// <summary>
        /// ID
        /// </summary>
        public System.Guid ID { get; set; }
    	/// <summary>
        /// 后台登录帐号
        /// </summary>
        public string sLoginAccout { get; set; }
    	/// <summary>
        /// 帐号面膜
        /// </summary>
        public string sPassWord { get; set; }
    	/// <summary>
        /// 手机号码
        /// </summary>
        public string sPhone { get; set; }
    	/// <summary>
        /// 姓名
        /// </summary>
        public string sName { get; set; }
    	/// <summary>
        /// 照片
        /// </summary>
        public string sHeadPicture { get; set; }
    	/// <summary>
        /// 绑定的角色主键ID
        /// </summary>
        public string sRoleId { get; set; }
    	/// <summary>
        /// 注册时间
        /// </summary>
        public System.DateTime dInsertTime { get; set; }
    	/// <summary>
        /// 上次登录时间
        /// </summary>
        public Nullable<System.DateTime> dLastLoginTime { get; set; }
    	/// <summary>
        /// 状态 0-冻结 1-正常
        /// </summary>
        public int iState { get; set; }
    	/// <summary>
        /// 逻辑删除标识
        /// </summary>
        public bool bIsDeleted { get; set; }
    	/// <summary>
        /// 是否是超级管理员
        /// </summary>
        public bool bIsSuper { get; set; }
    }
}
