//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDELINK_Client
    {
        public System.Guid ID { get; set; }
        public string sPhone { get; set; }
        public string sPassWord { get; set; }
        public string sCourtId { get; set; }
        public int iState { get; set; }
        public decimal dPrices { get; set; }
        public System.DateTime dRegisterTime { get; set; }
        public string sNickName { get; set; }
    }
}
