//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// CDELINK_Button
    /// </summary>
    public partial class CDELINK_Button
    {
    	/// <summary>
        /// ID
        /// </summary>
        public System.Guid ID { get; set; }
    	/// <summary>
        /// 按钮名称
        /// </summary>
        public string sButtonName { get; set; }
    	/// <summary>
        /// 按钮图标
        /// </summary>
        public string sButtonIcon { get; set; }
    	/// <summary>
        /// 所属菜单主键ID
        /// </summary>
        public string sMenuId { get; set; }
    	/// <summary>
        /// 按钮排序
        /// </summary>
        public int iOrder { get; set; }
    	/// <summary>
        /// 按钮标识
        /// </summary>
        public string sButtonSign { get; set; }
    }
}
