//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDELINK_Button
    {
        public System.Guid ID { get; set; }
        public string sButtonName { get; set; }
        public string sButtonIcon { get; set; }
        public string sMenuId { get; set; }
        public int iOrder { get; set; }
        public string sButtonSign { get; set; }
        public bool bIsToolbar { get; set; }
    }
}
