//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_Orders
    {
        public System.Guid ID { get; set; }
        public string sOpenId { get; set; }
        public string sOrderNo { get; set; }
        public Nullable<int> iOrderType { get; set; }
        public string sGoodsNo { get; set; }
        public string sGoodsName { get; set; }
        public decimal dGoodsPrices { get; set; }
        public decimal dPrices { get; set; }
        public decimal dAllPrices { get; set; }
        public decimal dDiscountPrices { get; set; }
        public System.DateTime dBookTime { get; set; }
        public Nullable<System.DateTime> dPayTime { get; set; }
        public Nullable<System.DateTime> dDoneTime { get; set; }
        public int iCount { get; set; }
        public string sReceiver { get; set; }
        public string sPhone { get; set; }
        public string sAddress { get; set; }
        public string sContent { get; set; }
        public string sActivity { get; set; }
        public string sIp { get; set; }
        public int iChannel { get; set; }
        public int iState { get; set; }
        public int iIntegral { get; set; }
        public string sGuige { get; set; }
        public string sLogisticsCompany { get; set; }
        public string sLogisticsNo { get; set; }
    }
}
