//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_ShopAddress
    {
        public System.Guid ID { get; set; }
        public string sOpenId { get; set; }
        public string sReceiver { get; set; }
        public string sPhone { get; set; }
        public string sProvince { get; set; }
        public string sCity { get; set; }
        public string sArea { get; set; }
        public string sAddress { get; set; }
        public bool bIsDefault { get; set; }
    }
}
