//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_WeChat
    {
        public System.Guid ID { get; set; }
        public string sWeChatName { get; set; }
        public string sOriginalId { get; set; }
        public string sAppId { get; set; }
        public string sAppSecret { get; set; }
        public string sToken { get; set; }
        public string sServerUrl { get; set; }
        public string sMchId { get; set; }
        public string sPayKey { get; set; }
    }
}
