//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourtEntities : DbContext
    {
        public CourtEntities()
            : base("name=CourtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CDELINK_AdminRole> CDELINK_AdminRole { get; set; }
        public virtual DbSet<CDELINK_AdminUser> CDELINK_AdminUser { get; set; }
        public virtual DbSet<CDELINK_Button> CDELINK_Button { get; set; }
        public virtual DbSet<CDELINK_Client> CDELINK_Client { get; set; }
        public virtual DbSet<CDELINK_Menu> CDELINK_Menu { get; set; }
        public virtual DbSet<CDELINK_WebSite> CDELINK_WebSite { get; set; }
        public virtual DbSet<CDELINK_WeChat> CDELINK_WeChat { get; set; }
        public virtual DbSet<CDELINK_WeChatMenu> CDELINK_WeChatMenu { get; set; }
        public virtual DbSet<CDELINK_WeChatNews> CDELINK_WeChatNews { get; set; }
        public virtual DbSet<CDELINK_WeChatNewsName> CDELINK_WeChatNewsName { get; set; }
        public virtual DbSet<CDELINK_WeChatConcern> CDELINK_WeChatConcern { get; set; }
        public virtual DbSet<CDELINK_WeChatKeyWord> CDELINK_WeChatKeyWord { get; set; }
        public virtual DbSet<ES_Client> ES_Client { get; set; }
        public virtual DbSet<ES_Goods> ES_Goods { get; set; }
        public virtual DbSet<ES_Orders> ES_Orders { get; set; }
        public virtual DbSet<ES_ShopAddress> ES_ShopAddress { get; set; }
    }
}
