//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
namespace EFModels
{
    using Common;
    using System.Data.Entity.Validation;
    using System.Text;
    
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourtEntities : DbContext
    {
        public CourtEntities()
            : base("name=CourtEntities")
        {
    		//开启数据库脚本跟踪
            this.Database.Log = s => Debug.WriteLine(s);
    
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CDELINK_AdminRole> CDELINK_AdminRole { get; set; }
        public virtual DbSet<CDELINK_AdminUser> CDELINK_AdminUser { get; set; }
        public virtual DbSet<CDELINK_Button> CDELINK_Button { get; set; }
        public virtual DbSet<CDELINK_Client> CDELINK_Client { get; set; }
        public virtual DbSet<CDELINK_Menu> CDELINK_Menu { get; set; }
    }
}
